services:
  php:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    container_name: symfony-php
    restart: unless-stopped
    volumes:
      - .:/var/www/symfony:delegated
      - symfony_var:/var/www/symfony/var
      - symfony_vendor:/var/www/symfony/vendor
    environment:
      - APP_ENV
      - APP_SECRET
      - DATABASE_URL
      - MESSENGER_TRANSPORT_DSN
      - MAILER_DSN
      - EMAIL_ADMIN
      - RECAPTCHA3_KEY
      - RECAPTCHA3_SECRET
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    depends_on:
      - db

  messenger:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    container_name: symfony-messenger
    restart: unless-stopped
    volumes:
      - .:/var/www/symfony:delegated
      - symfony_var:/var/www/symfony/var
      - symfony_vendor:/var/www/symfony/vendor
    environment:
      - APP_ENV
      - APP_SECRET
      - DATABASE_URL
      - MESSENGER_TRANSPORT_DSN
      - MARIADB_HOST
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    depends_on:
      - php
      - db
    command: php bin/console messenger:consume scheduler_default --no-interaction -vv

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony:delegated
      - symfony_var:/var/www/symfony/var
      - symfony_vendor:/var/www/symfony/vendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mariadb:11.2
    container_name: symfony-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  symfony_var:
  symfony_vendor:
